---
title: "R Notebook"
output: html_notebook
---

Read the XML using xml2

```{r}
library(xml2)
library(dplyr)
xml <- read_xml("t3300.xml")
tables <- xml_find_all(xml,".//Table")
```
for parsing tables that have a single dimension
```{r}
parse_table_1d <- function(table){
  ys <- xml_find_all(table,".//Y")
  time <- as.integer(xml_attr(ys,"t"))
  mortality <- xml_double(ys)
  data <- data.frame(t = time, q = mortality)
  data
}
parse_table_1d(tables[2])
```
for parsing tables that have a two dimensions

```{r}
parse_table_2d <- function(table_2d){
  ys_2d <- xml_find_all(table_2d,"./Values/Axis")
  time_2d <- xml_attr(ys_2d,"t")
  tester <- xml_find_all(ys_2d,"./Axis/Y")
  timer_ed <- as.integer(xml_attr(tester, "t"))
  mortality_2d <- xml_double(tester)
  merged_data <- data.frame()
  for (outer_axis in ys_2d){
    times_2d <- xml_find_all(outer_axis,"./Axis/Y")
    timer_2d <- as.integer(xml_attr(times_2d, "t"))
    mortal_2d <- xml_double(times_2d)
    age <- rep(as.integer(xml_attr(outer_axis, "t"),length(times_2d)))
    data_2d <- data.frame(age= age, t = timer_2d, q = mortal_2d)
    merged_data <- bind_rows(merged_data, data_2d)
  }
  return (merged_data)
}
parse_table_2d(tables[1])
```

Determine dimension of table and parse accordingly

```{r}
parse_tables <- function(xml)
{
  tables <- xml_find_all(xml, "./Table")
  result <- list()
  for (table in tables) {
    num_axes <- length(xml_find_all(table, ".//AxisDef"))
    if (num_axes == 2) {
      data <- parse_table_2d(table)
      result[[length(result)+1]] <- data
    }
    else {
      data <- parse_table_1d(table)
      result[[length(result)+1]] <- data
    }
  }
  return(result)
}
result <- parse_tables(xml)
result
```